---
- name: Check if Docker is installed
  ansible.builtin.shell: docker --version
  register: result
  check_mode: false
  changed_when: false
  failed_when: result.rc != 0

- name: Check if kubectl is installed
  ansible.builtin.shell: kubectl version --client
  register: result
  check_mode: false
  changed_when: false
  failed_when: result.rc != 0

- name: Check if RKE2 is installed
  ansible.builtin.shell: rke2 --version
  register: result
  check_mode: false
  changed_when: false

- name: Install RKE2
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sudo sh -
  register: result
  check_mode: false
  changed_when: false
  when: result.rc != 0

- name: Start the RKE2 service
  ansible.builtin.service:
    name: rke2-server.service
    state: started
    enabled: true

- name: make .kube directories
  ansible.builtin.file:
    path: "{{ item }}/.kube"
    state: directory
  loop:
    - /root
    - /home/tomer

- name: Copy .kubeconfig file to home directory root
  ansible.builtin.file:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /root/.kube/config
    owner: root
    group: root
    state: hard
    mode: 0600
    force: true

- name: Copy .kubeconfig file to home directory tomer
  ansible.builtin.file:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/tomer/.kube/config
    owner: tomer
    group: tomer
    state: hard
    mode: 0600
    force: true


- name: Run the Rancher UI
  community.docker.docker_container:
    name: rancher_ui
    image: rancher/rancher:v2.10.0
    state: started
    ports:
      - 80:80
      - 443:443
    privileged: true
    restart_policy: unless-stopped
    detach: true
